import mongoose from 'mongoose';
import { MultiPolygonSchema } from './geometry'

const SimidValuesSchema = mongoose.Schema({
      data_zone: String,
      Name: String,
      tot_pop_2011: Number,
      res_pop_2011: Number,
      hhc_nt_2011: Number,
      std_ara_ha: Number,
      std_area_km2: Number,
      shape_len: Number,
      shape_area: Number,
      intermediate_zone: String,
      council_area: String,
      total_population: Number,
      working_age_population: Number,
      simid_2020_rank: Number,
      simin_2020_percentile: Number,
      simid_2020_vigintile: Number,
      simid_2020_decile: Number,
      simid_2020_quintile: Number,
      simid_2020_income_domain_rank: Number,
      simid_2020_employment_domain_rank: Number,
      simid_2020_health_domain_rank: Number,
      simid_2020_education_domain_rank: Number,
      simid_2020_access_domain_rank: Number,
      simid_2020_crime_domain_rank: Number,
      simid_2020_housing_domain_rank: Number,
      income_rate: String,
      imcome_count: Number,
      employment_rate: String,
      employment_count: Number,
      cif: Number,
      alcohol: Number,
      drug: Number,
      smr: Number,
      depress: String,
      lbwt: String,
      emerg: String,
      attendance: String,
      attainment: String,
      no_qualifications: Number,
      not_participating: String,
      university: String,
      crime_count: String,
      crime_rate: Number,
      overcrowded_count: Number,
      no_cenral_heating_rate: String,
      drive_petrol: Number,
      drive_gp: Number,
      drive_post: Number,
      drive_primary: Number,
      drive_retail: Number,
      drive_secondary: Number,
      pt_gp: Number,
      pt_post: Number,
      pt_retail: Number,
      broadband: String,
})



const SimidRecordSchema = mongoose.Schema({
      geometry: MultiPolygonSchema,
      details: SimidValuesSchema,
});

export const SimidRecord = mongoose.model('simid', SimidRecordSchema);